{% set name = "conda-oci-mirror" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/channel-mirrors/conda-oci-mirror/archive/v{{ version }}.tar.gz
  sha256: 2e4d5b9baefcaf8d7951c14d66878cb4a5ef19a56960ae0af6714e430caad81e


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click
    - requests
    - oras-py 0.1.14
    - conda-package-handling

test:
  imports:
    - conda_oci_mirror
    - conda_oci_mirror.mirror
    - conda_oci_mirror.repo
  requires:
    - pip
  commands:
    - pip check
    - conda-oci --help

about:
  home: https://github.com/channel-mirrors/conda-oci-mirror
  summary: 'Tools to mirror conda packages to an OCI registry'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaimergp
    - wolfv
