{% set name = "conda-oci-mirror" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/channel-mirrors/conda-oci-mirror/archive/v{{ version }}.tar.gz
  sha256: 21d421a798753dcb8afcb1733d55d0f8c5f2748545b13cf44ec80b53fdf7d77f


build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click
    - requests
    - oras-py 0.1.14
    - conda-package-handling
    - zstandard

test:
  imports:
    - conda_oci_mirror
    - conda_oci_mirror.mirror
    - conda_oci_mirror.repo
  requires:
    - pip
  commands:
    - pip check
    - conda-oci --help

about:
  home: https://github.com/channel-mirrors/conda-oci-mirror
  summary: 'Tools to mirror conda packages to an OCI registry'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaimergp
    - wolfv
